server:
  port: ${port:10044}

logging:
  level:
    root: ${loglevel:INFO}
    #DEBUG

spring:
  ######################################
  #########  DB PROPERTIES #############
  ######################################

  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://34.135.239.235:5432/postgresdb}
    username: ${DATABASE_USERNAME:admin}
    password: ${DATABASE_PWD:test123}
    driver-class-name: ${DATABASE_DRIVERCLASS:org.postgresql.Driver}



camt54:
  db:
    validate_pacs008_pacs002_query: ${VALIDATE_PACS008_PACS002 :SELECT COUNT(1) FROM network_il.batch_tracker WHERE batch_id = :batchId AND msg_type IN ('pacs.008.001.09', 'pacs.002.001.11') AND status = 'Hold'}
    update_batch_tracker_hold_by_msgid_query: ${UPDATE_BT_HOLD_STATUS :UPDATE network_il.batch_tracker SET status = 'Hold' WHERE msg_id = :msgId}


topic:
  dispatchertopic: ${DISPATCHERTOPIC:DISPATCHERTOPIC}

batch-tracker:
  allowedMsgTypes:
    - ${BT_CAMT054:camt.054.001.08}

retry:
  transaction-audit:
    max-attempts: ${RETRY_TXN_MAX_ATTEMPTS:3}   # default 3
    backoff:
      delay: ${RETRY_TXN_BACKOFF_DELAY_MS:200}  # default 200
      multiplier: ${RETRY_TXN_BACKOFF_MULTIPLIER:2.0} # default 2.0



